/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\CodeNote\\Vue.js\\code\\yued-docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-8f9ff14c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8f9ff14c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-582ff14e",
    path: "/components/button.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-582ff14e").then(next)
    },
  },
  {
    name: "v-bf768fe4",
    path: "/components/cascader.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bf768fe4").then(next)
    },
  },
  {
    name: "v-a2b61364",
    path: "/components/carousel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a2b61364").then(next)
    },
  },
  {
    name: "v-3e8ac88e",
    path: "/components/grid.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e8ac88e").then(next)
    },
  },
  {
    name: "v-edb7ce24",
    path: "/components/collapse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-edb7ce24").then(next)
    },
  },
  {
    name: "v-15dfe238",
    path: "/components/input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15dfe238").then(next)
    },
  },
  {
    name: "v-2373b52e",
    path: "/components/menu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2373b52e").then(next)
    },
  },
  {
    name: "v-60bbe264",
    path: "/components/pagination.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60bbe264").then(next)
    },
  },
  {
    name: "v-1a44264e",
    path: "/components/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a44264e").then(next)
    },
  },
  {
    name: "v-1d696542",
    path: "/components/popover.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d696542").then(next)
    },
  },
  {
    name: "v-0ce5c930",
    path: "/components/table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ce5c930").then(next)
    },
  },
  {
    name: "v-b507f8e4",
    path: "/components/tabs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b507f8e4").then(next)
    },
  },
  {
    name: "v-7703e5ee",
    path: "/components/upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7703e5ee").then(next)
    },
  },
  {
    name: "v-4b27ca3e",
    path: "/components/toast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b27ca3e").then(next)
    },
  },
  {
    name: "v-9269fda2",
    path: "/install/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9269fda2").then(next)
    },
  },
  {
    path: "/install/index.html",
    redirect: "/install/"
  },
  {
    name: "v-552bdcd1",
    path: "/get-started/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-552bdcd1").then(next)
    },
  },
  {
    path: "/get-started/index.html",
    redirect: "/get-started/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]