/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Yue UI",
  "description": "UI 框架",
  "base": "/yued/",
  "headTags": [],
  "pages": [
    {
      "title": "一个好用的 UI 框架",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-8f9ff14c",
      "path": "/"
    },
    {
      "title": "Button 按钮",
      "frontmatter": {
        "title": "Button 按钮"
      },
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-582ff14e",
      "path": "/components/button.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Cascader 级联选择器",
      "frontmatter": {
        "title": "Cascader 级联选择器"
      },
      "regularPath": "/components/cascader.html",
      "relativePath": "components/cascader.md",
      "key": "v-bf768fe4",
      "path": "/components/cascader.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Carousel 走马灯",
      "frontmatter": {
        "title": "Carousel 走马灯"
      },
      "regularPath": "/components/carousel.html",
      "relativePath": "components/carousel.md",
      "key": "v-a2b61364",
      "path": "/components/carousel.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Grid 栅格",
      "frontmatter": {
        "title": "Grid 栅格"
      },
      "regularPath": "/components/grid.html",
      "relativePath": "components/grid.md",
      "key": "v-3e8ac88e",
      "path": "/components/grid.html",
      "headers": [
        {
          "level": 3,
          "title": "Row Attributes",
          "slug": "row-attributes"
        },
        {
          "level": 3,
          "title": "Col Attributes",
          "slug": "col-attributes"
        }
      ]
    },
    {
      "title": "Collapse 折叠面板",
      "frontmatter": {
        "title": "Collapse 折叠面板"
      },
      "regularPath": "/components/collapse.html",
      "relativePath": "components/collapse.md",
      "key": "v-edb7ce24",
      "path": "/components/collapse.html",
      "headers": [
        {
          "level": 3,
          "title": "Collapse Attributes",
          "slug": "collapse-attributes"
        },
        {
          "level": 3,
          "title": "CollapseItem Attributes",
          "slug": "collapseitem-attributes"
        }
      ]
    },
    {
      "title": "Input 输入框",
      "frontmatter": {
        "title": "Input 输入框"
      },
      "regularPath": "/components/input.html",
      "relativePath": "components/input.md",
      "key": "v-15dfe238",
      "path": "/components/input.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Menu 导航菜单",
      "frontmatter": {
        "title": "Menu 导航菜单"
      },
      "regularPath": "/components/menu.html",
      "relativePath": "components/menu.md",
      "key": "v-2373b52e",
      "path": "/components/menu.html",
      "headers": [
        {
          "level": 3,
          "title": "Menu Attributes",
          "slug": "menu-attributes"
        },
        {
          "level": 3,
          "title": "MenuItem Attributes",
          "slug": "menuitem-attributes"
        }
      ]
    },
    {
      "title": "Pagination 分页",
      "frontmatter": {
        "title": "Pagination 分页"
      },
      "regularPath": "/components/pagination.html",
      "relativePath": "components/pagination.md",
      "key": "v-60bbe264",
      "path": "/components/pagination.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Layout 布局",
      "frontmatter": {
        "title": "Layout 布局"
      },
      "regularPath": "/components/layout.html",
      "relativePath": "components/layout.md",
      "key": "v-1a44264e",
      "path": "/components/layout.html",
      "headers": [
        {
          "level": 3,
          "title": "Header Attributes",
          "slug": "header-attributes"
        },
        {
          "level": 3,
          "title": "Sider Attributes",
          "slug": "sider-attributes"
        },
        {
          "level": 3,
          "title": "Footer Attributes",
          "slug": "footer-attributes"
        }
      ]
    },
    {
      "title": "Popover 弹出框",
      "frontmatter": {
        "title": "Popover 弹出框"
      },
      "regularPath": "/components/popover.html",
      "relativePath": "components/popover.md",
      "key": "v-1d696542",
      "path": "/components/popover.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Table 表格",
      "frontmatter": {
        "title": "Table 表格"
      },
      "regularPath": "/components/table.html",
      "relativePath": "components/table.md",
      "key": "v-0ce5c930",
      "path": "/components/table.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Tabs 标签页",
      "frontmatter": {
        "title": "Tabs 标签页"
      },
      "regularPath": "/components/tabs.html",
      "relativePath": "components/tabs.md",
      "key": "v-b507f8e4",
      "path": "/components/tabs.html",
      "headers": [
        {
          "level": 3,
          "title": "Tabs Attributes",
          "slug": "tabs-attributes"
        },
        {
          "level": 3,
          "title": "TabsItem Attributes",
          "slug": "tabsitem-attributes"
        },
        {
          "level": 3,
          "title": "TabsPane Attributes",
          "slug": "tabspane-attributes"
        }
      ]
    },
    {
      "title": "Upload 上传",
      "frontmatter": {
        "title": "Upload 上传"
      },
      "regularPath": "/components/upload.html",
      "relativePath": "components/upload.md",
      "key": "v-7703e5ee",
      "path": "/components/upload.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "Toast 全局提示",
      "frontmatter": {
        "title": "Toast 全局提示"
      },
      "regularPath": "/components/toast.html",
      "relativePath": "components/toast.md",
      "key": "v-4b27ca3e",
      "path": "/components/toast.html",
      "headers": [
        {
          "level": 3,
          "title": "Attributes",
          "slug": "attributes"
        }
      ]
    },
    {
      "title": "安装",
      "frontmatter": {},
      "regularPath": "/install/",
      "relativePath": "install/README.md",
      "key": "v-9269fda2",
      "path": "/install/"
    },
    {
      "title": "快速开始",
      "frontmatter": {},
      "regularPath": "/get-started/",
      "relativePath": "get-started/README.md",
      "key": "v-552bdcd1",
      "path": "/get-started/"
    }
  ],
  "themeConfig": {
    "lastUpdated": "最后更新时间",
    "sidebar": [
      {
        "title": "入门",
        "children": [
          "/install/",
          "/get-started/"
        ]
      },
      {
        "title": "组件",
        "children": [
          "/components/button",
          "/components/grid",
          "/components/layout",
          "/components/popover",
          "/components/tabs",
          "/components/toast",
          "/components/pagination",
          "/components/table",
          "/components/menu",
          "/components/collapse",
          "/components/cascader",
          "/components/carousel",
          "/components/upload",
          "/components/input"
        ]
      }
    ],
    "nav": [
      {
        "text": "主页",
        "link": ""
      },
      {
        "text": "文档",
        "link": "/guide/"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/carsonhuang520/yued"
      }
    ]
  }
}